<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class ChapterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('chapters')->insert([
            [
                'chapter_name' => 'Chương 1: Mở đầu',
                'chapter_number' =>'1',
                'creation_id' => '5',
                'chapter_content' => '.......
                " - Tha thu... Lôi Phá Quyền...!
                Những tia sét vẫn còn bao quanh nắm đấm của tôi như xác nhận lại chưởng lực vừa rồi từ đâu mà ra, con ma cà rồng hộc máu tươi đau đớn nói không lên lời, rồi nó gồng hết sức lại rống lên một tiếng cực lớn... "
                Lâm chăm chú đọc bộ truyện "Tôi là đạo sĩ" của tác giả Nguyễn Điệp. Hắn rất thích bộ truyện này, luôn mơ ước trở nên bá đạo như nhân vật Đ trong truyện, đi khắp nơi trừ gian diệt ác với những khả năng dị thường...
                Mạc Lâm - một thiếu niên 17 tuổi, hiện đang theo học tại một trường nội trú tư thục của thành phố, lực học cũng không phải là yếu nhưng cũng tạm đủ để lên lớp đều đều. Sở thích của cậu là tìm hiểu về những bí ẩn tâm linh trong cuộc sống và đọc các tiểu thuyết kinh dị.
                Ước mơ của Lâm là trở nên bá đạo, sở hữu nhiều dị năng như các nhân vật chính trong các bộ truyện như "Đạo sĩ tản mạn kì", "Vùng đất vô hình" hay cực ngầu, nhiều tài phép như huyền thoại Lâm Chánh Anh... Vậy nên Lâm luôn chìm đắm trong mớ suy nghĩ viễn vông, tư tưởng luôn ở trên mây khiến vẻ bề ngoài lúc nào cũng khù khờ, lờ đờ như mấy thằng thiểu năng.
                ...
                - Lâm! Lâm...xuống dọn dẹp nhà cửa phụ mẹ coi! Đi học cả tuần về rồi cứ ở trên phòng suốt là sao?
                Chẳng là hôm nay chủ nhật, Lâm về nhà vào cuối tuần để nghỉ ngơi và chuẩn bị cho tuần học mới. Và như thường lệ lại nhốt mình trong phòng để nghiền ngẫm mấy bộ truyện yêu thích. Cho tới khi nghe mẹ gọi.
                - Dạ...! Con xuống liền... - Lâm uể oải đáp, mắt rời khỏi màn hình laptop, gấp máy lại rồi bước xuống lầu.
                - Mày coi dọn dẹp nhà kho cho gọn lại, để mẹ đem mớ đồ cũ cất vô cho đỡ chật nhà, đồ đạc gì đâu tha về cả đống...
                Lâm miễn cưỡng bước vào nhà kho cùng cây chổi, dọn nhà kho là công việc mà cậu ghét nhất...
                - Khụ khụ! Bụi bặm gì dữ vậy trời! Lâm vừa quét vừa than thở.
                - Ế! Có cái gì vậy ta? – Cậu chú ý đến một chiếc hộp nhỏ đặt trên nóc tủ đồ cũ - "Nguyễn Đ nhờ vớ được cái hộp của bà nội mà trở thành đạo sĩ bá đạo, có khi nào..." - Lâm thầm nghĩ, mừng rỡ khi mình đang trong hoàn cảnh giống nhân vật Đ, biết đâu lớ ngớ lại vớ huy chương thì bá cmn đạo rồi.
                Nhanh chóng, Lâm lôi ngay chiếc hộp xuống, phủi lớp bụi dày bám trên nắp và mở ra. Tim đập thình thịch, mồ hôi chảy ướt cả trán, mọi giác quan hoạt động hết công suất.
                Hai tay run run mở chốt khóa, đẩy nhẹ nắp hộp ra. Lâm tưởng tượng trong hộp sẽ là một quyển sách cũ kỹ ghi đủ mọi loại bùa chú ấn quyết trừ tà.
                Nhưng đời thì méo bao giờ như mơ...à nhầm, méo như truyện... bên trong chiếc hộp chỉ vỏn vẹn một quyển vở hiệu....ba cây bút cùng những dòng chữ và nhiều con số:
                "Cô 6 bán chè: 26 - 50 ngàn.
                Chị 7 đầu xóm: 39 - 70 ngàn.
                ......."
                - Mắc thằng bố nó! Làm mừng hụt - Lâm bực bội ném chiếc hộp vào một góc rồi nhanh chóng dọn dẹp lại nhà kho sau đó về phòng nghiền ngẫm tiếp những chương cuối dang dở của bộ "Tôi là đạo sĩ". Mà có cái Lâm rất bực đó là tác giả Nguyễn Điệp viết truyện rất ngắn, vừa liếc cái là hết ngay nên lúc nào cũng phải đợi tầm 3-4 chap truyện Lâm mới bắt đầu đọc.
                ________________
                Sáng đầu tuần...
                - Ê Lâm, dậy đi, cô gọi mày kìa - Tuấn - bạn thân của Lâm đang lay mạnh.
                - A...a...a...Tha thu...Lôi Phá Quyền...! - Lâm đứng bật dậy la lớn, hai tay đẩy mạnh về trước làm bà cô già giật mình xém chút té ngửa.
                Cả lớp được một trận cười vỡ bụng, Tuấn lắc đầu ngao ngán...
                - Ra hành lang đứng ngay cho tôi...!
                _________
                -Còn nữa-'
            ],
            [
                'chapter_name' => 'Chương 2: Cái chết bí ẩn 1',
                'creation_id' => '5',
                'chapter_number' =>'2',
                'chapter_content' => 'Khuya hôm đó...
                Như thường lệ, Lâm cùng Tuấn ôm laptop nghiền ngẫm tiếp mấy bộ truyện ma. Đêm nào hai thằng cũng thức đến gần sáng để ngấu nghiến từng bộ một. Còn Nam và Cường đã ngủ say từ 8-9 giờ tối (phòng ký túc có 4 người, gồm Lâm, Tuấn, Nam và Cường). Khác với Lâm mỗi lần thức khuya là sáng hôm sau lại ngủ gục trong giờ, Tuấn có thể thức thâu đêm mà sáng ra vẫn tỉnh táo như thường.
                - Thôi đi ngủ mày ơi, gần 2 giờ rồi! - Tuấn uể oải vươn vai ngáp.
                - Đợi chút, đọc xong chương này đã!
                - Dẹp, đi ngủ đi! Mai lại ra hành lang nữa bây giờ! - Tuấn bực bội đóng luôn con lap lại rồi ôm leo lên giường luôn.
                Tuy có hơi tiếc mấy chương truyện, nhưng Lâm vẫn phải miễn cưỡng chui vào giường đi ngủ vì thực nó cũng chẳng muốn Tuấn bực lên rồi lại nện cho mấy cái...
                Trằn trọc mãi không ngủ được, Lâm bật dậy, mở cửa bước ra ngoài hóng gió. Giờ này ra ngoài thì không lo bị bắt, vì quản sinh, bảo vệ đã ngủ say tự đời nào rồi, may ra giờ này còn mấy con chó hoang sủa nhau ỏm tỏi ngoài kia.
                Nhè nhẹ đẩy một bên cửa, Lâm bước ra ngoài vươn vai múa may cho giãn gân cốt. Trước phòng của Lâm là một cây xà cừ lớn, bên dưới gốc cây là vài cái ghế đá nhỏ để học sinh ngồi tán dóc. Lâm bước đến gốc cây, tựa lưng vào ghế tận hưởng những cơn gió nhẹ nhàng của đêm mùa thu. Lá cây đưa xào xạc, cả khoảng sân trống vắng, yên tĩnh, chốc chốc lại có vài tiếng chó tru tréo đến rợn người. Bóng đèn sáng rọi bóng cành cây hằn trên tường, trên mặt đất tạo thành những hình thù quái dị mà những người có trí tưởng tượng phong phú ắt sẽ rùng mình...
                Gió nhè nhẹ đưa, vài chiếc lá nằm dưới đất khẽ bay...
                Lâm nhắm nghiền mắt tận hưởng làn gió nhẹ...
                Cành cây đưa nhẹ, lá khua xào xạc...
                Một bóng đen có vẻ như được treo lơ lửng trên cành cây bằng một sợi dây thừng in trên mặt đất...
                Lâm tình cờ mở mắt, thấy bóng đen kỳ dị thì quay lại phía sau lưng mình...
                ...
                Cả trường xôn xao vì cái chết kì lạ của một nam sinh. Cậu là P - bạn học lớp cũ của Lâm, được phát hiện chết trong tư thế treo cổ trên cành cây xà cừ, chỗ Lâm ngồi đêm qua, đương nhiên người phát hiên là Lâm. Thân thể tím tái, cứng đờ; mặt tím ngắt, lưỡi thè ra ngoài trông rất kinh dị cùng với đôi mắt mở to, trợn tròn cùng những tia máu đỏ ngầu. Đặc biệt, không phát hiện thấy bất cứ công cụ nào giúp P leo lên để...cột dây tự tử, không một chiếc ghế, không một chiếc thang; vậy làm thế nào mà một người bình thường có thể treo mình lên tận một cành cây cao đến hơn 3 mét, hơn nữa...sợi dây dùng để treo cổ không phải là dây thừng bình thường, có vẻ là một nguyên liệu từ thiên nhiên với bề mặt nhẵn bóng, màu trắng đục như tơ?
                Lúc khám nghiệm tử thi không hề có bất cứ dấu vết nào cho thấy nạn nhân bị giết trước đó rồi đưa lên cây; cũng không có dấu hiệu nào cho thấy P tự tử: một nam sinh hoà đồng, vui vẻ với mọi người; hăng hái, tích cực trong mọi việc và luôn yêu đời như P thì làm sao có thể nghĩ đến con đường tự sát được. Riêng có một điểm rất đặc biệt mà phía công an giữ kín: "Phía cổ trái của P có hai lỗ nhỏ trông như vết rắn cắn nhưng không có vết răng nhỏ xung quanh, và có nhiều vết móng tay cào xước ở phần lưng và ngực."
                Bằng kinh nghiệm lâu năm đọc truyện kinh dị, Lâm dám chắc chắn rằng P chết là do một thế lực nào đó vượt xa khỏi hiểu biết của con người gây ra. Một thứ nào đó đã đưa P lên cây bằng năng lượng vô hình, treo P lên và cắm phập những chiếc răng nanh sắc nhọn vào cổ cậu, dùng những móng tay sắc nhọn cào cấu cơ thể trong khi cậu đang vùng vẫy và dùng năng lực cản trở không để thoát ra một âm thành nào trong đêm yên tĩnh...một cái chết im lặng...
                Đêm qua, khi phát hiện cái xác, chính Lâm là người tìm cách gỡ xuống trong khi tri hô. Cũng chính cậu là người đầu tiên thực hiện việc khám nghiệm sơ qua. Đồng tử giãn hẹp, cơ thể vẫn còn hơi ấm chính là điều mà Lâm băn khoăn (ông nội của Lâm là chủ một trại mai táng, do thường xuyên đi theo ông nên Lâm có học được chút ít kiến thức về tử thi). Rõ ràng trong vòng 30 phút đó ở sân trường chỉ có Lâm, vậy mà chính cậu cũng chẳng phát hiện sớm hơn trong khi cây xà cừ đối diện phòng mình. Mọi suy diễn về một thế lực vô hình của Lâm có vẻ đúng...
                Đêm sau ngày phát hiện cái chết của P...
                - Lâm...Lâm...mày phải giúp tao...dưới gối nằm của tao...
                Lâm giật mình tỉnh giấc, mồ hôi vã ra như tắm. Lâm vừa trải qua một giấc mơ kì lạ: P đứng ngay đầu giường mình trong bộ dạng hết sức kinh dị; lưỡi thè ra dài đến tận cổ, thấp thoáng là dấu hằn sợi dây, mặt tái xanh trông rất đáng sợ...P đứng đó gọi Lâm, nhắc đi nhắc lại về thứ gì đó dưới gối nằm của mình và cầu mong Lâm giúp đỡ...? Dù đã miễn nhiễm với những thứ kinh dị nhưng Lâm vẫn cảm thấy rất sợ hãi, phần vì lần đầu trực tiếp mơ thấy người chết, phần vì cái chết của P quá bí ẩn, phần vì từng là bạn bè nên cảm thấy bất an, lo rằng P sẽ theo ám mình như trong những câu truyện kinh dị hay đọc...
                Lâm quyết định ngày hôm sau sẽ thử đến phòng P tìm xem có gì bí ẩn dưới gối nằm của cậu hay không...
                __________
                -Còn nữa-'
            ],
            [
                'chapter_name' => 'Chương 1: Cái chết bí ẩn',
                'creation_id' => '1',
                'chapter_number' =>'1',
                'chapter_content' => 'Khuya hôm đó...
                Như thường lệ, Lâm cùng Tuấn ôm laptop nghiền ngẫm tiếp mấy bộ truyện ma. Đêm nào hai thằng cũng thức đến gần sáng để ngấu nghiến từng bộ một. Còn Nam và Cường đã ngủ say từ 8-9 giờ tối (phòng ký túc có 4 người, gồm Lâm, Tuấn, Nam và Cường). Khác với Lâm mỗi lần thức khuya là sáng hôm sau lại ngủ gục trong giờ, Tuấn có thể thức thâu đêm mà sáng ra vẫn tỉnh táo như thường.
                - Thôi đi ngủ mày ơi, gần 2 giờ rồi! - Tuấn uể oải vươn vai ngáp.
                - Đợi chút, đọc xong chương này đã!
                - Dẹp, đi ngủ đi! Mai lại ra hành lang nữa bây giờ! - Tuấn bực bội đóng luôn con lap lại rồi ôm leo lên giường luôn.
                Tuy có hơi tiếc mấy chương truyện, nhưng Lâm vẫn phải miễn cưỡng chui vào giường đi ngủ vì thực nó cũng chẳng muốn Tuấn bực lên rồi lại nện cho mấy cái...
                Trằn trọc mãi không ngủ được, Lâm bật dậy, mở cửa bước ra ngoài hóng gió. Giờ này ra ngoài thì không lo bị bắt, vì quản sinh, bảo vệ đã ngủ say tự đời nào rồi, may ra giờ này còn mấy con chó hoang sủa nhau ỏm tỏi ngoài kia.
                Nhè nhẹ đẩy một bên cửa, Lâm bước ra ngoài vươn vai múa may cho giãn gân cốt. Trước phòng của Lâm là một cây xà cừ lớn, bên dưới gốc cây là vài cái ghế đá nhỏ để học sinh ngồi tán dóc. Lâm bước đến gốc cây, tựa lưng vào ghế tận hưởng những cơn gió nhẹ nhàng của đêm mùa thu. Lá cây đưa xào xạc, cả khoảng sân trống vắng, yên tĩnh, chốc chốc lại có vài tiếng chó tru tréo đến rợn người. Bóng đèn sáng rọi bóng cành cây hằn trên tường, trên mặt đất tạo thành những hình thù quái dị mà những người có trí tưởng tượng phong phú ắt sẽ rùng mình...
                Gió nhè nhẹ đưa, vài chiếc lá nằm dưới đất khẽ bay...
                Lâm nhắm nghiền mắt tận hưởng làn gió nhẹ...
                Cành cây đưa nhẹ, lá khua xào xạc...
                Một bóng đen có vẻ như được treo lơ lửng trên cành cây bằng một sợi dây thừng in trên mặt đất...
                Lâm tình cờ mở mắt, thấy bóng đen kỳ dị thì quay lại phía sau lưng mình...
                ...
                Cả trường xôn xao vì cái chết kì lạ của một nam sinh. Cậu là P - bạn học lớp cũ của Lâm, được phát hiện chết trong tư thế treo cổ trên cành cây xà cừ, chỗ Lâm ngồi đêm qua, đương nhiên người phát hiên là Lâm. Thân thể tím tái, cứng đờ; mặt tím ngắt, lưỡi thè ra ngoài trông rất kinh dị cùng với đôi mắt mở to, trợn tròn cùng những tia máu đỏ ngầu. Đặc biệt, không phát hiện thấy bất cứ công cụ nào giúp P leo lên để...cột dây tự tử, không một chiếc ghế, không một chiếc thang; vậy làm thế nào mà một người bình thường có thể treo mình lên tận một cành cây cao đến hơn 3 mét, hơn nữa...sợi dây dùng để treo cổ không phải là dây thừng bình thường, có vẻ là một nguyên liệu từ thiên nhiên với bề mặt nhẵn bóng, màu trắng đục như tơ?
                Lúc khám nghiệm tử thi không hề có bất cứ dấu vết nào cho thấy nạn nhân bị giết trước đó rồi đưa lên cây; cũng không có dấu hiệu nào cho thấy P tự tử: một nam sinh hoà đồng, vui vẻ với mọi người; hăng hái, tích cực trong mọi việc và luôn yêu đời như P thì làm sao có thể nghĩ đến con đường tự sát được. Riêng có một điểm rất đặc biệt mà phía công an giữ kín: "Phía cổ trái của P có hai lỗ nhỏ trông như vết rắn cắn nhưng không có vết răng nhỏ xung quanh, và có nhiều vết móng tay cào xước ở phần lưng và ngực."
                Bằng kinh nghiệm lâu năm đọc truyện kinh dị, Lâm dám chắc chắn rằng P chết là do một thế lực nào đó vượt xa khỏi hiểu biết của con người gây ra. Một thứ nào đó đã đưa P lên cây bằng năng lượng vô hình, treo P lên và cắm phập những chiếc răng nanh sắc nhọn vào cổ cậu, dùng những móng tay sắc nhọn cào cấu cơ thể trong khi cậu đang vùng vẫy và dùng năng lực cản trở không để thoát ra một âm thành nào trong đêm yên tĩnh...một cái chết im lặng...
                Đêm qua, khi phát hiện cái xác, chính Lâm là người tìm cách gỡ xuống trong khi tri hô. Cũng chính cậu là người đầu tiên thực hiện việc khám nghiệm sơ qua. Đồng tử giãn hẹp, cơ thể vẫn còn hơi ấm chính là điều mà Lâm băn khoăn (ông nội của Lâm là chủ một trại mai táng, do thường xuyên đi theo ông nên Lâm có học được chút ít kiến thức về tử thi). Rõ ràng trong vòng 30 phút đó ở sân trường chỉ có Lâm, vậy mà chính cậu cũng chẳng phát hiện sớm hơn trong khi cây xà cừ đối diện phòng mình. Mọi suy diễn về một thế lực vô hình của Lâm có vẻ đúng...
                Đêm sau ngày phát hiện cái chết của P...
                - Lâm...Lâm...mày phải giúp tao...dưới gối nằm của tao...
                Lâm giật mình tỉnh giấc, mồ hôi vã ra như tắm. Lâm vừa trải qua một giấc mơ kì lạ: P đứng ngay đầu giường mình trong bộ dạng hết sức kinh dị; lưỡi thè ra dài đến tận cổ, thấp thoáng là dấu hằn sợi dây, mặt tái xanh trông rất đáng sợ...P đứng đó gọi Lâm, nhắc đi nhắc lại về thứ gì đó dưới gối nằm của mình và cầu mong Lâm giúp đỡ...? Dù đã miễn nhiễm với những thứ kinh dị nhưng Lâm vẫn cảm thấy rất sợ hãi, phần vì lần đầu trực tiếp mơ thấy người chết, phần vì cái chết của P quá bí ẩn, phần vì từng là bạn bè nên cảm thấy bất an, lo rằng P sẽ theo ám mình như trong những câu truyện kinh dị hay đọc...
                Lâm quyết định ngày hôm sau sẽ thử đến phòng P tìm xem có gì bí ẩn dưới gối nằm của cậu hay không...
                __________
                -Còn nữa-'
            ],
            [
                'chapter_name' => 'Chương 2: Cái chết bí ẩn 2',
                'chapter_number' =>'2',
                'creation_id' => '1',
                'chapter_content' => 'Khuya hôm đó...
                Như thường lệ, Lâm cùng Tuấn ôm laptop nghiền ngẫm tiếp mấy bộ truyện ma. Đêm nào hai thằng cũng thức đến gần sáng để ngấu nghiến từng bộ một. Còn Nam và Cường đã ngủ say từ 8-9 giờ tối (phòng ký túc có 4 người, gồm Lâm, Tuấn, Nam và Cường). Khác với Lâm mỗi lần thức khuya là sáng hôm sau lại ngủ gục trong giờ, Tuấn có thể thức thâu đêm mà sáng ra vẫn tỉnh táo như thường.
                - Thôi đi ngủ mày ơi, gần 2 giờ rồi! - Tuấn uể oải vươn vai ngáp.
                - Đợi chút, đọc xong chương này đã!
                - Dẹp, đi ngủ đi! Mai lại ra hành lang nữa bây giờ! - Tuấn bực bội đóng luôn con lap lại rồi ôm leo lên giường luôn.
                Tuy có hơi tiếc mấy chương truyện, nhưng Lâm vẫn phải miễn cưỡng chui vào giường đi ngủ vì thực nó cũng chẳng muốn Tuấn bực lên rồi lại nện cho mấy cái...
                Trằn trọc mãi không ngủ được, Lâm bật dậy, mở cửa bước ra ngoài hóng gió. Giờ này ra ngoài thì không lo bị bắt, vì quản sinh, bảo vệ đã ngủ say tự đời nào rồi, may ra giờ này còn mấy con chó hoang sủa nhau ỏm tỏi ngoài kia.
                Nhè nhẹ đẩy một bên cửa, Lâm bước ra ngoài vươn vai múa may cho giãn gân cốt. Trước phòng của Lâm là một cây xà cừ lớn, bên dưới gốc cây là vài cái ghế đá nhỏ để học sinh ngồi tán dóc. Lâm bước đến gốc cây, tựa lưng vào ghế tận hưởng những cơn gió nhẹ nhàng của đêm mùa thu. Lá cây đưa xào xạc, cả khoảng sân trống vắng, yên tĩnh, chốc chốc lại có vài tiếng chó tru tréo đến rợn người. Bóng đèn sáng rọi bóng cành cây hằn trên tường, trên mặt đất tạo thành những hình thù quái dị mà những người có trí tưởng tượng phong phú ắt sẽ rùng mình...
                Gió nhè nhẹ đưa, vài chiếc lá nằm dưới đất khẽ bay...
                Lâm nhắm nghiền mắt tận hưởng làn gió nhẹ...
                Cành cây đưa nhẹ, lá khua xào xạc...
                Một bóng đen có vẻ như được treo lơ lửng trên cành cây bằng một sợi dây thừng in trên mặt đất...
                Lâm tình cờ mở mắt, thấy bóng đen kỳ dị thì quay lại phía sau lưng mình...
                ...
                Cả trường xôn xao vì cái chết kì lạ của một nam sinh. Cậu là P - bạn học lớp cũ của Lâm, được phát hiện chết trong tư thế treo cổ trên cành cây xà cừ, chỗ Lâm ngồi đêm qua, đương nhiên người phát hiên là Lâm. Thân thể tím tái, cứng đờ; mặt tím ngắt, lưỡi thè ra ngoài trông rất kinh dị cùng với đôi mắt mở to, trợn tròn cùng những tia máu đỏ ngầu. Đặc biệt, không phát hiện thấy bất cứ công cụ nào giúp P leo lên để...cột dây tự tử, không một chiếc ghế, không một chiếc thang; vậy làm thế nào mà một người bình thường có thể treo mình lên tận một cành cây cao đến hơn 3 mét, hơn nữa...sợi dây dùng để treo cổ không phải là dây thừng bình thường, có vẻ là một nguyên liệu từ thiên nhiên với bề mặt nhẵn bóng, màu trắng đục như tơ?
                Lúc khám nghiệm tử thi không hề có bất cứ dấu vết nào cho thấy nạn nhân bị giết trước đó rồi đưa lên cây; cũng không có dấu hiệu nào cho thấy P tự tử: một nam sinh hoà đồng, vui vẻ với mọi người; hăng hái, tích cực trong mọi việc và luôn yêu đời như P thì làm sao có thể nghĩ đến con đường tự sát được. Riêng có một điểm rất đặc biệt mà phía công an giữ kín: "Phía cổ trái của P có hai lỗ nhỏ trông như vết rắn cắn nhưng không có vết răng nhỏ xung quanh, và có nhiều vết móng tay cào xước ở phần lưng và ngực."
                Bằng kinh nghiệm lâu năm đọc truyện kinh dị, Lâm dám chắc chắn rằng P chết là do một thế lực nào đó vượt xa khỏi hiểu biết của con người gây ra. Một thứ nào đó đã đưa P lên cây bằng năng lượng vô hình, treo P lên và cắm phập những chiếc răng nanh sắc nhọn vào cổ cậu, dùng những móng tay sắc nhọn cào cấu cơ thể trong khi cậu đang vùng vẫy và dùng năng lực cản trở không để thoát ra một âm thành nào trong đêm yên tĩnh...một cái chết im lặng...
                Đêm qua, khi phát hiện cái xác, chính Lâm là người tìm cách gỡ xuống trong khi tri hô. Cũng chính cậu là người đầu tiên thực hiện việc khám nghiệm sơ qua. Đồng tử giãn hẹp, cơ thể vẫn còn hơi ấm chính là điều mà Lâm băn khoăn (ông nội của Lâm là chủ một trại mai táng, do thường xuyên đi theo ông nên Lâm có học được chút ít kiến thức về tử thi). Rõ ràng trong vòng 30 phút đó ở sân trường chỉ có Lâm, vậy mà chính cậu cũng chẳng phát hiện sớm hơn trong khi cây xà cừ đối diện phòng mình. Mọi suy diễn về một thế lực vô hình của Lâm có vẻ đúng...
                Đêm sau ngày phát hiện cái chết của P...
                - Lâm...Lâm...mày phải giúp tao...dưới gối nằm của tao...
                Lâm giật mình tỉnh giấc, mồ hôi vã ra như tắm. Lâm vừa trải qua một giấc mơ kì lạ: P đứng ngay đầu giường mình trong bộ dạng hết sức kinh dị; lưỡi thè ra dài đến tận cổ, thấp thoáng là dấu hằn sợi dây, mặt tái xanh trông rất đáng sợ...P đứng đó gọi Lâm, nhắc đi nhắc lại về thứ gì đó dưới gối nằm của mình và cầu mong Lâm giúp đỡ...? Dù đã miễn nhiễm với những thứ kinh dị nhưng Lâm vẫn cảm thấy rất sợ hãi, phần vì lần đầu trực tiếp mơ thấy người chết, phần vì cái chết của P quá bí ẩn, phần vì từng là bạn bè nên cảm thấy bất an, lo rằng P sẽ theo ám mình như trong những câu truyện kinh dị hay đọc...
                Lâm quyết định ngày hôm sau sẽ thử đến phòng P tìm xem có gì bí ẩn dưới gối nằm của cậu hay không...
                __________
                -Còn nữa-'
            ],
            [
                'chapter_name' => 'Chương 3: Cái chết bí ẩn',
                'chapter_number' =>'3',
                'creation_id' => '1',
                'chapter_content' => 'Khuya hôm đó...
                Như thường lệ, Lâm cùng Tuấn ôm laptop nghiền ngẫm tiếp mấy bộ truyện ma. Đêm nào hai thằng cũng thức đến gần sáng để ngấu nghiến từng bộ một. Còn Nam và Cường đã ngủ say từ 8-9 giờ tối (phòng ký túc có 4 người, gồm Lâm, Tuấn, Nam và Cường). Khác với Lâm mỗi lần thức khuya là sáng hôm sau lại ngủ gục trong giờ, Tuấn có thể thức thâu đêm mà sáng ra vẫn tỉnh táo như thường.
                - Thôi đi ngủ mày ơi, gần 2 giờ rồi! - Tuấn uể oải vươn vai ngáp.
                - Đợi chút, đọc xong chương này đã!
                - Dẹp, đi ngủ đi! Mai lại ra hành lang nữa bây giờ! - Tuấn bực bội đóng luôn con lap lại rồi ôm leo lên giường luôn.
                Tuy có hơi tiếc mấy chương truyện, nhưng Lâm vẫn phải miễn cưỡng chui vào giường đi ngủ vì thực nó cũng chẳng muốn Tuấn bực lên rồi lại nện cho mấy cái...
                Trằn trọc mãi không ngủ được, Lâm bật dậy, mở cửa bước ra ngoài hóng gió. Giờ này ra ngoài thì không lo bị bắt, vì quản sinh, bảo vệ đã ngủ say tự đời nào rồi, may ra giờ này còn mấy con chó hoang sủa nhau ỏm tỏi ngoài kia.
                Nhè nhẹ đẩy một bên cửa, Lâm bước ra ngoài vươn vai múa may cho giãn gân cốt. Trước phòng của Lâm là một cây xà cừ lớn, bên dưới gốc cây là vài cái ghế đá nhỏ để học sinh ngồi tán dóc. Lâm bước đến gốc cây, tựa lưng vào ghế tận hưởng những cơn gió nhẹ nhàng của đêm mùa thu. Lá cây đưa xào xạc, cả khoảng sân trống vắng, yên tĩnh, chốc chốc lại có vài tiếng chó tru tréo đến rợn người. Bóng đèn sáng rọi bóng cành cây hằn trên tường, trên mặt đất tạo thành những hình thù quái dị mà những người có trí tưởng tượng phong phú ắt sẽ rùng mình...
                Gió nhè nhẹ đưa, vài chiếc lá nằm dưới đất khẽ bay...
                Lâm nhắm nghiền mắt tận hưởng làn gió nhẹ...
                Cành cây đưa nhẹ, lá khua xào xạc...
                Một bóng đen có vẻ như được treo lơ lửng trên cành cây bằng một sợi dây thừng in trên mặt đất...
                Lâm tình cờ mở mắt, thấy bóng đen kỳ dị thì quay lại phía sau lưng mình...
                ...
                Cả trường xôn xao vì cái chết kì lạ của một nam sinh. Cậu là P - bạn học lớp cũ của Lâm, được phát hiện chết trong tư thế treo cổ trên cành cây xà cừ, chỗ Lâm ngồi đêm qua, đương nhiên người phát hiên là Lâm. Thân thể tím tái, cứng đờ; mặt tím ngắt, lưỡi thè ra ngoài trông rất kinh dị cùng với đôi mắt mở to, trợn tròn cùng những tia máu đỏ ngầu. Đặc biệt, không phát hiện thấy bất cứ công cụ nào giúp P leo lên để...cột dây tự tử, không một chiếc ghế, không một chiếc thang; vậy làm thế nào mà một người bình thường có thể treo mình lên tận một cành cây cao đến hơn 3 mét, hơn nữa...sợi dây dùng để treo cổ không phải là dây thừng bình thường, có vẻ là một nguyên liệu từ thiên nhiên với bề mặt nhẵn bóng, màu trắng đục như tơ?
                Lúc khám nghiệm tử thi không hề có bất cứ dấu vết nào cho thấy nạn nhân bị giết trước đó rồi đưa lên cây; cũng không có dấu hiệu nào cho thấy P tự tử: một nam sinh hoà đồng, vui vẻ với mọi người; hăng hái, tích cực trong mọi việc và luôn yêu đời như P thì làm sao có thể nghĩ đến con đường tự sát được. Riêng có một điểm rất đặc biệt mà phía công an giữ kín: "Phía cổ trái của P có hai lỗ nhỏ trông như vết rắn cắn nhưng không có vết răng nhỏ xung quanh, và có nhiều vết móng tay cào xước ở phần lưng và ngực."
                Bằng kinh nghiệm lâu năm đọc truyện kinh dị, Lâm dám chắc chắn rằng P chết là do một thế lực nào đó vượt xa khỏi hiểu biết của con người gây ra. Một thứ nào đó đã đưa P lên cây bằng năng lượng vô hình, treo P lên và cắm phập những chiếc răng nanh sắc nhọn vào cổ cậu, dùng những móng tay sắc nhọn cào cấu cơ thể trong khi cậu đang vùng vẫy và dùng năng lực cản trở không để thoát ra một âm thành nào trong đêm yên tĩnh...một cái chết im lặng...
                Đêm qua, khi phát hiện cái xác, chính Lâm là người tìm cách gỡ xuống trong khi tri hô. Cũng chính cậu là người đầu tiên thực hiện việc khám nghiệm sơ qua. Đồng tử giãn hẹp, cơ thể vẫn còn hơi ấm chính là điều mà Lâm băn khoăn (ông nội của Lâm là chủ một trại mai táng, do thường xuyên đi theo ông nên Lâm có học được chút ít kiến thức về tử thi). Rõ ràng trong vòng 30 phút đó ở sân trường chỉ có Lâm, vậy mà chính cậu cũng chẳng phát hiện sớm hơn trong khi cây xà cừ đối diện phòng mình. Mọi suy diễn về một thế lực vô hình của Lâm có vẻ đúng...
                Đêm sau ngày phát hiện cái chết của P...
                - Lâm...Lâm...mày phải giúp tao...dưới gối nằm của tao...
                Lâm giật mình tỉnh giấc, mồ hôi vã ra như tắm. Lâm vừa trải qua một giấc mơ kì lạ: P đứng ngay đầu giường mình trong bộ dạng hết sức kinh dị; lưỡi thè ra dài đến tận cổ, thấp thoáng là dấu hằn sợi dây, mặt tái xanh trông rất đáng sợ...P đứng đó gọi Lâm, nhắc đi nhắc lại về thứ gì đó dưới gối nằm của mình và cầu mong Lâm giúp đỡ...? Dù đã miễn nhiễm với những thứ kinh dị nhưng Lâm vẫn cảm thấy rất sợ hãi, phần vì lần đầu trực tiếp mơ thấy người chết, phần vì cái chết của P quá bí ẩn, phần vì từng là bạn bè nên cảm thấy bất an, lo rằng P sẽ theo ám mình như trong những câu truyện kinh dị hay đọc...
                Lâm quyết định ngày hôm sau sẽ thử đến phòng P tìm xem có gì bí ẩn dưới gối nằm của cậu hay không...
                __________
                -Còn nữa-'
            ],
            [
                'chapter_name' => 'Chương 4: Cái chết bí ẩn',
                'chapter_number' =>'4',
                'creation_id' => '1',
                'chapter_content' => 'Khuya hôm đó...
                Như thường lệ, Lâm cùng Tuấn ôm laptop nghiền ngẫm tiếp mấy bộ truyện ma. Đêm nào hai thằng cũng thức đến gần sáng để ngấu nghiến từng bộ một. Còn Nam và Cường đã ngủ say từ 8-9 giờ tối (phòng ký túc có 4 người, gồm Lâm, Tuấn, Nam và Cường). Khác với Lâm mỗi lần thức khuya là sáng hôm sau lại ngủ gục trong giờ, Tuấn có thể thức thâu đêm mà sáng ra vẫn tỉnh táo như thường.
                - Thôi đi ngủ mày ơi, gần 2 giờ rồi! - Tuấn uể oải vươn vai ngáp.
                - Đợi chút, đọc xong chương này đã!
                - Dẹp, đi ngủ đi! Mai lại ra hành lang nữa bây giờ! - Tuấn bực bội đóng luôn con lap lại rồi ôm leo lên giường luôn.
                Tuy có hơi tiếc mấy chương truyện, nhưng Lâm vẫn phải miễn cưỡng chui vào giường đi ngủ vì thực nó cũng chẳng muốn Tuấn bực lên rồi lại nện cho mấy cái...
                Trằn trọc mãi không ngủ được, Lâm bật dậy, mở cửa bước ra ngoài hóng gió. Giờ này ra ngoài thì không lo bị bắt, vì quản sinh, bảo vệ đã ngủ say tự đời nào rồi, may ra giờ này còn mấy con chó hoang sủa nhau ỏm tỏi ngoài kia.
                Nhè nhẹ đẩy một bên cửa, Lâm bước ra ngoài vươn vai múa may cho giãn gân cốt. Trước phòng của Lâm là một cây xà cừ lớn, bên dưới gốc cây là vài cái ghế đá nhỏ để học sinh ngồi tán dóc. Lâm bước đến gốc cây, tựa lưng vào ghế tận hưởng những cơn gió nhẹ nhàng của đêm mùa thu. Lá cây đưa xào xạc, cả khoảng sân trống vắng, yên tĩnh, chốc chốc lại có vài tiếng chó tru tréo đến rợn người. Bóng đèn sáng rọi bóng cành cây hằn trên tường, trên mặt đất tạo thành những hình thù quái dị mà những người có trí tưởng tượng phong phú ắt sẽ rùng mình...
                Gió nhè nhẹ đưa, vài chiếc lá nằm dưới đất khẽ bay...
                Lâm nhắm nghiền mắt tận hưởng làn gió nhẹ...
                Cành cây đưa nhẹ, lá khua xào xạc...
                Một bóng đen có vẻ như được treo lơ lửng trên cành cây bằng một sợi dây thừng in trên mặt đất...
                Lâm tình cờ mở mắt, thấy bóng đen kỳ dị thì quay lại phía sau lưng mình...
                ...
                Cả trường xôn xao vì cái chết kì lạ của một nam sinh. Cậu là P - bạn học lớp cũ của Lâm, được phát hiện chết trong tư thế treo cổ trên cành cây xà cừ, chỗ Lâm ngồi đêm qua, đương nhiên người phát hiên là Lâm. Thân thể tím tái, cứng đờ; mặt tím ngắt, lưỡi thè ra ngoài trông rất kinh dị cùng với đôi mắt mở to, trợn tròn cùng những tia máu đỏ ngầu. Đặc biệt, không phát hiện thấy bất cứ công cụ nào giúp P leo lên để...cột dây tự tử, không một chiếc ghế, không một chiếc thang; vậy làm thế nào mà một người bình thường có thể treo mình lên tận một cành cây cao đến hơn 3 mét, hơn nữa...sợi dây dùng để treo cổ không phải là dây thừng bình thường, có vẻ là một nguyên liệu từ thiên nhiên với bề mặt nhẵn bóng, màu trắng đục như tơ?
                Lúc khám nghiệm tử thi không hề có bất cứ dấu vết nào cho thấy nạn nhân bị giết trước đó rồi đưa lên cây; cũng không có dấu hiệu nào cho thấy P tự tử: một nam sinh hoà đồng, vui vẻ với mọi người; hăng hái, tích cực trong mọi việc và luôn yêu đời như P thì làm sao có thể nghĩ đến con đường tự sát được. Riêng có một điểm rất đặc biệt mà phía công an giữ kín: "Phía cổ trái của P có hai lỗ nhỏ trông như vết rắn cắn nhưng không có vết răng nhỏ xung quanh, và có nhiều vết móng tay cào xước ở phần lưng và ngực."
                Bằng kinh nghiệm lâu năm đọc truyện kinh dị, Lâm dám chắc chắn rằng P chết là do một thế lực nào đó vượt xa khỏi hiểu biết của con người gây ra. Một thứ nào đó đã đưa P lên cây bằng năng lượng vô hình, treo P lên và cắm phập những chiếc răng nanh sắc nhọn vào cổ cậu, dùng những móng tay sắc nhọn cào cấu cơ thể trong khi cậu đang vùng vẫy và dùng năng lực cản trở không để thoát ra một âm thành nào trong đêm yên tĩnh...một cái chết im lặng...
                Đêm qua, khi phát hiện cái xác, chính Lâm là người tìm cách gỡ xuống trong khi tri hô. Cũng chính cậu là người đầu tiên thực hiện việc khám nghiệm sơ qua. Đồng tử giãn hẹp, cơ thể vẫn còn hơi ấm chính là điều mà Lâm băn khoăn (ông nội của Lâm là chủ một trại mai táng, do thường xuyên đi theo ông nên Lâm có học được chút ít kiến thức về tử thi). Rõ ràng trong vòng 30 phút đó ở sân trường chỉ có Lâm, vậy mà chính cậu cũng chẳng phát hiện sớm hơn trong khi cây xà cừ đối diện phòng mình. Mọi suy diễn về một thế lực vô hình của Lâm có vẻ đúng...
                Đêm sau ngày phát hiện cái chết của P...
                - Lâm...Lâm...mày phải giúp tao...dưới gối nằm của tao...
                Lâm giật mình tỉnh giấc, mồ hôi vã ra như tắm. Lâm vừa trải qua một giấc mơ kì lạ: P đứng ngay đầu giường mình trong bộ dạng hết sức kinh dị; lưỡi thè ra dài đến tận cổ, thấp thoáng là dấu hằn sợi dây, mặt tái xanh trông rất đáng sợ...P đứng đó gọi Lâm, nhắc đi nhắc lại về thứ gì đó dưới gối nằm của mình và cầu mong Lâm giúp đỡ...? Dù đã miễn nhiễm với những thứ kinh dị nhưng Lâm vẫn cảm thấy rất sợ hãi, phần vì lần đầu trực tiếp mơ thấy người chết, phần vì cái chết của P quá bí ẩn, phần vì từng là bạn bè nên cảm thấy bất an, lo rằng P sẽ theo ám mình như trong những câu truyện kinh dị hay đọc...
                Lâm quyết định ngày hôm sau sẽ thử đến phòng P tìm xem có gì bí ẩn dưới gối nằm của cậu hay không...
                __________
                -Còn nữa-'
            ]

        ]);
    }
}
